const states = new Map();
states.set("Alabama","AL");
states.set("Alaska","AK");
states.set("Alberta","AB");
states.set("American Samoa","AS");
states.set("Arizona","AZ");
states.set("Arkansas","AR");
states.set("Armed Forces (AE)","AE");
states.set("Armed Forces Americas","AA");
states.set("Armed Forces Pacific","AP");
states.set("British Columbia","BC");
states.set("California","CA");
states.set("Colorado","CO");
states.set("Connecticut","CT");
states.set("Delaware","DE");
states.set("District Of Columbia","DC");
states.set("Florida","FL");
states.set("Georgia","GA");
states.set("Guam","GU");
states.set("Hawaii","HI");
states.set("Idaho","ID");
states.set("Illinois","IL");
states.set("Indiana","IN");
states.set("Iowa","IA");
states.set("Kansas","KS");
states.set("Kentucky","KY");
states.set("Louisiana","LA");
states.set("Maine","ME");
states.set("Manitoba","MB");
states.set("Maryland","MD");
states.set("Massachusetts","MA");
states.set("Michigan","MI");
states.set("Minnesota","MN");
states.set("Mississippi","MS");
states.set("Missouri","MO");
states.set("Montana","MT");
states.set("Nebraska","NE");
states.set("Nevada","NV");
states.set("New Brunswick","NB");
states.set("New Hampshire","NH");
states.set("New Jersey","NJ");
states.set("New Mexico","NM");
states.set("New York","NY");
states.set("Newfoundland","NF");
states.set("North Carolina","NC");
states.set("North Dakota","ND");
states.set("Northwest Territories","NT");
states.set("Nova Scotia","NS");
states.set("Nunavut","NU");
states.set("Ohio","OH");
states.set("Oklahoma","OK");
states.set("Ontario","ON");
states.set("Oregon","OR");
states.set("Pennsylvania","PA");
states.set("Prince Edward Island","PE");
states.set("Puerto Rico","PR");
states.set("Quebec","QC");
states.set("Rhode Island","RI");
states.set("Saskatchewan","SK");
states.set("South Carolina","SC");
states.set("South Dakota","SD");
states.set("Tennessee","TN");
states.set("Texas","TX");
states.set("Utah","UT");
states.set("Vermont","VT");
states.set("Virgin Islands","VI");
states.set("Virginia","VA");
states.set("Washington","WA");
states.set("West Virginia","WV");
states.set("Wisconsin","WI");
states.set("Wyoming","WY");
states.set("Yukon Territory","YT");